services:
  app:
    container_name: app-dev
    deploy:
       resources:
           limits:
              cpus: '1.00'
              memory: '513M'
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file:
      - ./env/.env.dev
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:latest
    # restart: always
    volumes:
       - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
       - "27017:27017"
    healthcheck:
      test: >
        bash -c "mongo --quiet --host mongo --eval 'rs.status().myState===1'"
      interval: 3s
      timeout: 2s
      retries: 10
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip_all"]