services:
  app:
    container_name: app-dev
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file:
      - ./env/.env.dev
  mongo:
    container_name: db-mongo
    image: mongo:latest
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
       - "27017:27017"
  mongo-gui:
    container_name: mongo-gui
    image: mongo-express:latest
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
