services:
  app:
    container_name: app-dev
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
       mongo:
          condition: service_healthy
    env_file:
      - ./env/.env.dev
  mongo:
    container_name: db-mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
       - ./mongo/data:/data/db
       - ./mongo/init/init-replica-user.sh:/docker-entrypoint-initdb.d/init-replica-user.sh:ro
       - ./mongo/keyfile/mongo-keyfile:/etc/mongo-keyfile:ro
    ports:
       - "27017:27017"
    healthcheck:
       test: ["CMD", "mongosh", "--eval", "db.adminCommand({ ping: 1 })"]
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 30s
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]